name: "releases"
 
on:
  push:
     branches:
       - main
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${{vars.TAG}}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{vars.TAG}}
          
    - name: create release
      run: |
       curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases \
        -d '{"tag_name":"p1.0.0","target_commitish":"master","name":"p1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
#     - name: search release 
#       run: |
#        curl -L \
#         -H "Accept: application/vnd.github+json" \
#         -H "Authorization: Bearer  ${{ secrets.TOKEN }}"\
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#         https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases/latest
#     - name: update release
#       run: |
#        curl -L \
#         -X PATCH \
#         -H "Accept: application/vnd.github+json" \
#         -H "Authorization: Bearer ${{ secrets.TOKEN }}"\
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#         https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases/129848372 \
#         -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"test","body":"Description of the release","draft":false,"prerelease":false}'
