name: "releases"
 
on:
  push:
     branches:
       - main
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: create release
      run: |
         curl -L \
         -X PATCH \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer 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"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases/RELEASE_ID \
         -d '{"tag_name":"v1.0.2","target_commitish":"master","name":"v1.0.1","body":"Description of the release","draft":false,"prerelease":false}'






