name: "releases"
 
on:
  push:
     branches:
       - main
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${{vars.TAG}}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{vars.TAG}}
          
    - name: search release
      run: |
       curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        http://api.github.com/repos/sherif7z7/ci_with_github_actions/releases
    - name: search release
      run: |
       curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases/99689007 \
        -d '{"tag_name":"v1.0.1","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false}'
