name: Releases
on:
  push:
    branches:
      - main
      
jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.github_token }}

      - name: create release
        run: |
         curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer  ${{ secrets.git_token }}"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/sherif7z7/ci_with_github_actions/releases \
         -d '{"tag_name":"v1.0.0","target_commitish":"main","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
