name: "releases"
 
on:
  push:
     branches:
       - main
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
    - name: search release
      run: |
       curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        http://api.github.com/repos/sherif7z7/ci_with_github_actions/releases
